spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
        - id : customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
server:
  port: 8083
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true


