### replacing localhost with container names

spring:
  application:
    name: Apigateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id : customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
server:
  port: 8083
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true


