spring:
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  application:
    name: Notification
  datasource:
    username: 'root'
    url: jdbc:postgresql://localhost:5432/notification
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

server:
  port: 8082
