server:
  port: 8081
spring:
  application:
    name: Fraud
  datasource:
    username: 'root'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
